image: node:latest

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/

services:
  - mongo

variables:
  DB_HOST: mongo
  DB_USER: admin
  DB_PASSWORD: ''
  DB_DATABASE: dbtest

before_script:
  - node -v
  - which node
  - cp .env.example .env
  - cp .env.example .env.test
  - chmod 755 ./ace
  - npm install --silent --no-optional

test:
  script:
    - ./ace migration:run
    - npm run lint
    - npm run test
