language: node_js
node_js:
  - node
  - 7.0.0
services: mongodb
before_script:
  - mongo test_lucid --eval 'db.createUser({user:"test",pwd:"test",roles:["dbOwner"]});'
sudo: false
install:
  - npm -g install @adonisjs/cli
  - npm install --no-optional
  - cp .env.example .env
  - chmod 755 ./ace
  #- chmod 777 storage
script:
  - ./ace migration:run
  - npm run lint
  - npm run test
