language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
node_js:
- node
- 5.3.0
- 4.0.0
services: mongodb
before_script:
#- mongo dbtest --eval 'db.addUser("test", "test");'
sudo: false
install:
- npm install --no-optional
- cp .env.example .env.test
- cp .env.example .env
script:
#- ./ace migration:run
- npm run lint
- npm run test
