language: node_js
env:
  - DB_HOST: mongo
  - DB_USER: admin
  - DB_PASSWORD: ''
  - DB_DATABASE: dbtest
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
node_js:
- node
- 5.3.0
- 4.0.0
services: mongodb
before_script:
#- mongo dbtest --eval 'db.addUser("test", "test");'
sudo: false
install:
- npm install --no-optional
- cp .env .env.test
script:
- npm run test
