version: 2
jobs:
  test:
    docker:
      - image: circleci/node:latest
      - image: mongo:3.6.8
    steps:
      - run:
        name: add mongodb test user
        command: mongo admin --eval 'db.createUser({ user: "test", pwd: "test", roles: [{ role: "userAdminAnyDatabase", db: "admin" }]})'
      - checkout
      - run: 
          name: npm install
          command: npm install
      - run:
          name: copy env file
          command: cp .env.example .env
      - run:
          name: Test
          command: 'npm test'
      - run:
          name: Generate code coverage
          command: 'npm run coverage'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
